### ISSUE TITLE
Notes for use with caddy server

### ISSUE THREAD

**Issue by apiontek** [yurt-page/cgi-ubus#2]
Sharing in case it helps anyone: I got this working with caddy server on OpenWrt.

- [Required caddy plugin `aksdb/caddy-cgi/v2`](https://github.com/aksdb/caddy-cgi)
- [My blog notes](https://73k.us/blog/caddy-on-openwrt-with-access-to-luci)
- [Inspiration/reference](https://sigeryang.net/2022/02/12/caddy-openwrt-luci/)

Working (for me) Caddyfile config:

```
{
	order cgi before respond
}

localhost, 192.168.1.1, router, router.home {
	tls internal
	root * /www
	file_server

	cgi /cgi-bin/cgi-backup* /www/cgi-bin/cgi-backup {
		script_name /cgi-bin/cgi-backup
	}
	cgi /cgi-bin/cgi-download* /www/cgi-bin/cgi-download {
		script_name /cgi-bin/cgi-download
	}
	cgi /cgi-bin/cgi-exec* /www/cgi-bin/cgi-exec {
		script_name /cgi-bin/cgi-exec
	}
	cgi /cgi-bin/cgi-upload* /www/cgi-bin/cgi-upload {
		script_name /cgi-bin/cgi-upload
	}
	cgi /cgi-bin/luci* /www/cgi-bin/luci {
		script_name /cgi-bin/luci
	}
	cgi /ubus* /etc/caddy/ubus.sh {
		script_name /ubus
	}
}
```

**Comment by stokito** [comment]
Thank you. What is a reason to use the Caddy with Ubus?

**Comment by apiontek** [comment]
[Caddy is a webserver](https://caddyserver.com/), so, similar to how you have instructions for BusyBox httpd and Lighttpd, I wanted to use only Caddy on my openwrt device, while still using LuCI. I think the only way to do this makes use of your script per the [reference](https://sigeryang.net/2022/02/12/caddy-openwrt-luci/) linked perviously, but if there's a better or more efficient way I'm interested!

**Comment by stokito** [comment]
@apiontek sorry, I answered from a phone so the question sounds stupid. Basically the Luci works without the `/ubus` endpoint.
It makes a requests to it's own endpoint `/cgi-bin/luci/admin/ubus` which is a Lua script that forwards the request to the local ubus.
I needed the separate CGI script because for my project @yurt-page I used it for a blog separately without the Luci. And then I started using Lighttpd in parallel to Luci+uhttpd but I wish to get rid of the Lighttpd and ideally use BusyBox httpd which is only 8kb for a very cheap devices.

So my question is: what wasn't worked for you so that you needed the CGI script? I just wondered. Maybe you can simplify your setup.

Basically if your router is powerful enough then you can run the uhttpd+luci on a separate port and then just reverse proxy from the Caddy. Or even access directly.
My old 16mb router TL-WR1043ND is totally fine for running both Lighttpd and uhttpd in parallel.
The Caddy is written in Go and its binary is huge and this is not ideal chose for the routers. This also adds some confusion and curiosity to me.
I never used it but most people whom I know used it just because it issues certs easily. If that's also your main reason then you may try the acme.sh which also has a luci app. I documented it on OpenWrt wiki.

For a reverse proxy you may try a TinyProxy or even compile the BusyBox httpd with the proxy option (but it's too basic).

P.S. Speaking about your article. Thank you, when I started developing for OpenWrt I found that no that much information and any blog post was important for me.

Please note that the Caddy already have some binaries for MIPS. So you may try them. Here is said that you need a mips64 build https://openwrt.org/toh/ubiquiti/edgerouter_4

But even if you wish to compile then you can make a cross compile:
`GOOS=linux GOARCH=mips64 go build`
Then you don't need to install the go on your router.

If you have a then you can create a Wiki page for Caddy  here 
https://openwrt.org/docs/guide-user/services/webserver/start

The registration must be approved but I can just create a page with links to your article.

**Comment by stokito** [comment]
@apiontek To compile try `GOARCH=mipsle GOMIPS=softfloat go build`

**Comment by apiontek** [comment]
Thanks for the advice - It might take me a week or two to scrounge the time to test this all out but I'll report back when I can and see about adding to the community documentation too.

I'm on an edgerouter-4 and none of the pre-built mips Caddy binaries worked for me, but perhaps the cross compile could work!

**Comment by apiontek** [comment]
Thanks again for your info. I had reason to upgrade the er4 to openwrt 22.03.3 this morning and review my setup.

I note that as soon as I log in to LuCI (served by uhttpd, no caddy), in Firefox dev Network panel I see tons of requests to /ubus/?[13-digit-num] - since those are showing in my browser it seems like whatever web server is used would need to be able to handle /ubus/ ... I was also using collectd & luci statistics, which seemed to require /ubus requests from the browser to get graphs.

That said, while I was able to find the correct GO envs for cross-compiling (`GOOS=linux GOARCH=mips64 GOMIPS64=softfloat` worked for my edgerouter 4's cavium octeon), I had already been reconsidering using AdGuard Home (another large (37MB) golang binary).

I originally had bigger plans for running caddy but over time have changed my mind about the more complicated setup. In the end, caddy was only there "because I could do it," and chiefly reverse-proxying AdGuard Home.

I'm now looking to do less after an upgrade, so I'll be dropping AdGuardHome and Caddy from my setup. I'm even dropping collectd and the extra luci statistics because I am highly unlikely to ever look at them!

I do like caddy's ease of setup and I use it elsewhere, but I don't really need certs for the LAN admin on my router (and I can use self-signed for that anyway.

So, thanks again for your info! Nudged me to streamline my openwrt config here. And when I get more time I'd like to contribute more directly to the community. I can already see some things I could add to the edgerouter-4 wiki page...

**Comment by stokito** [comment]
Chrome hiding the full URL so try to click on the request and see in details the full URL
![image](https://user-images.githubusercontent.com/415502/213497639-374d8d6d-f4a4-4ed9-882b-394477621fe1.png)
Interesting but looks like on my LUCI I also see the request to /ubus but that may be some plugin (I have dozen of them).

Your router is powerful and the Caddy is great so anyway I think that many people may find your work useful. I'm using my router for self hosting and a personal cloud with photos and music. This may be interesting to you to try.

**Comment by ttyS0** [comment]
@apiontek Hi, I am glad to know that my original post is helpful to you. Recently I have revised my Caddyfile after I received others' emails on problems they encountered with my config, thus urges [my revision](https://sigeryang.net/2022/02/12/caddy-openwrt-luci/).

Considering that the post was published 16 months ago and Caddyfile spec actually changes from time to time, it is finally updated now. It now handles CGI programs under `/www/cgi-bin` in a more flexible way and supports self-signed TLS which acts like `luci-ssl`. (Of course you can instead configure a hostname for HTTPS block and get Automatic TLS experience.)

Hope this also help you and those who love Caddy and OpenWrt.

```
{
	order cgi before respond
	order file_server last

	# skip_install_trust
	# auto_https disable_redirects
	# default_sni openwrt.local
}

(luci) {
	root * /www
	route /cgi-bin* {
		@exists {
			file cgi-bin/{path.1} =404
		}
		handle @exists {
			uri strip_prefix {file_match.relative}
			cgi * /www/{file_match.relative} {
				script_name {file_match.relative}
			}
		}
	}
	cgi /ubus* ubus.sh {
		script_name /ubus
	}
	file_server
	redir / /cgi-bin/luci
}

http:// {
	import luci
}

# https:// {
# 	tls internal {
# 		on_demand
# 	}
# 	import luci
# }
```
